### ISSUE TITLE
How to rotate the image to standard view?

### ISSUE THREAD

**Issue by JunMa11** [neheller/kits19#9]
Dear organizers,
Thanks for organizing the excellent challenge.

I want to rotate the image to the standard view and write the code, but it does not help.
Would it be possible for you to give me some instructions?

Following is my code.
```python
import numpy as np
import nibabel as nb
import os

filepath = r'H:\Data\kits19\data'
savepath = r'H:\Data\kits19\preData'
if os.path.exists(savepath) is False: os.mkdir(savepath)

STD_AXCODES = ('S', 'A', 'R')
def do_reorientation(data_array, init_axcodes, final_axcodes):
    """
    Performs the reorientation (changing order of axes).

    :param data_array: Array to reorient
    :param init_axcodes: Initial orientation
    :param final_axcodes: Target orientation
    :return data_reoriented: New data array in its reoriented form
    """
    ornt_init = nb.orientations.axcodes2ornt(init_axcodes)
    ornt_fin = nb.orientations.axcodes2ornt(final_axcodes)
    if np.array_equal(ornt_init, ornt_fin):
        return data_array
    if np.any(np.isnan(ornt_init)) or np.any(np.isnan(ornt_fin)):
        raise ValueError
    try:
        ornt_transf = nb.orientations.ornt_transform(ornt_init, ornt_fin)
        data_reoriented = nb.orientations.apply_orientation(data_array, ornt_transf)
    except (ValueError, IndexError):
        raise ValueError

    return data_reoriented


filenames = os.listdir(filepath)
i = 0
for name in filenames[0:1]:
    img_nii = nb.load(os.path.join(filepath, name+'\\imaging.nii.gz'))
    img_data = img_nii.get_data()
    
    label_data = nb.load(os.path.join(filepath, name+'\\segmentation.nii.gz')).get_data()
    # reorientation to standard view
    _axcodes = tuple(nb.aff2axcodes(img_nii.affine)) # affine is a 4*4 matrix
    img_data = do_reorientation(img_data, _axcodes, STD_AXCODES)
    label_data = do_reorientation(label_data, _axcodes, STD_AXCODES)
    
    img_save_name = 'kidneyvol-' + str(i) + '.nii.gz'
    label_save_name = 'kidneymask-'+ str(i) + '.nii.gz'
#    new_affine = np.zeros_like(img_nii.affine)
#    new_affine[0][0] = img_nii.affine[2][2]
#    new_affine[2][2] = img_nii.affine[0][0]
    # save results
    save_img_nii = nb.Nifti1Image(img_data, img_nii.affine, img_nii.header)
    nb.save(save_img_nii, os.path.join(savepath, img_save_name))
    
    save_label_nii = nb.Nifti1Image(label_data, img_nii.affine, img_nii.header)
    nb.save(save_label_nii, os.path.join(savepath, label_save_name))
```
**Results:**
![Markdown](http://i1.bvimg.com/595387/e7a9334dd0dc3b2d.png)

Looking forward to your reply!
Best regards,
Edward

**Comment by neheller** [comment]
Hi Edward, 

Thanks for bringing this up, I seem to have goofed on the affine attributes. The following snip after your call to `nb.load` should serve as a workaround
```python3
img_nii.affine[:-1,:-1] = np.flip(img_nii.affine[:-1, :-1], axis=1)
```
I will fix this in the next training set release.

Nick

**Comment by neheller** [comment]
The affine matrices have corrected in the amended training data release. This should work on the new data, please feel free to reopen if you still run into trouble.

**Comment by neheller** [comment]
Oops - this is still a problem. I seem to have left the diagonal component in while assigning spacing to its proper spot. Really sorry about this, will fix it ASAP.

**Comment by neheller** [comment]
Fixed in latest commit.

**Comment by dericdesta** [comment]
Hi @neheller, the orientation seems to be standard view now, thanks. But I think the orientation (and hence the spacing) is still wrong (see, e.g., case `case_00000`).
